export ZSH="$HOME/.oh-my-zsh"



# === theme ===
source ~/.oh-my-zsh/custom/themes/headline.zsh-theme
HEADLINE_USER_PREFIX=' '
HEADLINE_PATH_PREFIX=' '
HEADLINE_BRANCH_PREFIX=' '
HEADLINE_STATUS_TO_STATUS='|'
HEADLINE_LINE_MODE=off
HEADLINE_DO_GIT_STATUS_COUNTS=true
HEADLINE_DO_GIT_STATUS_OMIT_ONE=true
HEADLINE_DO_ERR=true
HEADLINE_DO_CLOCK=true
HEADLINE_CLOCK_FORMAT='%l:%M:%S %p '



# === Oh My Zsh ===
source $ZSH/oh-my-zsh.sh
source $ZSH/oh-my-zsh-private.sh



# === "special" plugins ===
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
